In [8]:
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  9 13:16:03 2019

@author: CDS
"""

import pandas as pd
import tensorflow as tf
import io

### constant data
'''
xaa = [[1,1,1,-1,-1,-1,1,1,1]]
y_aa = [[1]]
'''

#import data from local csv
col_names = ['Y','A1','A2','A3','A4']
from google.colab import files
uploaded = files.upload()

pima = pd.read_csv(io.StringIO(uploaded['FinalData.csv'].decode('utf-8')),header = 0,names = col_names)
# load dataset
#pima = pd.read_csv("C:/Users/CDS/Desktop/FinalData.csv", header=0,names=col_names)
pimaObj = pima.iloc[:,:].values

#split dataset in features and target variable
feature_cols = ['A1','A2','A3','A4']
X = pima[feature_cols] # Features
target = ['Y']
y = pima[target] # Target variable

X = X.astype('int')
y = y.astype('int')

#NN that takes 9 inputs and returns 1 output via 2 hidden layers for size conversion
def neural(x,y_):
    ### induction
    # 1x9 input -> 9x9 hidden sigmoid -> 9x1 hidden sigmoid -> 1x1 sigmoid output
    
    # Layer 0 = the x2 inputs
    x0 = tf.constant( x  , dtype=tf.float32 )
    y0 = tf.constant( y_ , dtype=tf.float32 )
    
    # Layer 1 = the 9x9 hidden sigmoid
    m1 = tf.Variable( tf.random_uniform( [4,4] , minval=0 , maxval=1 , dtype=tf.float32  ))
    b1 = tf.Variable( tf.random_uniform( [4]   , minval=0 , maxval=1 , dtype=tf.float32  ))
    h1 = tf.sigmoid( tf.matmul( x0,m1 ) + b1 )

    # Layer 2 = the 9x1 hidden sigmoid
    m2 = tf.Variable( tf.random_uniform( [4,1] , minval=0 , maxval=1 , dtype=tf.float32  ))
    b2 = tf.Variable( tf.random_uniform( [1]   , minval=0 , maxval=1 , dtype=tf.float32  ))
    h2 = tf.sigmoid( tf.matmul( h1,m2 ) + b2 )
    
    # Layer 3 = the 1x1 sigmoid output
    m3 = tf.Variable( tf.random_uniform( [1,1] , minval=0 , maxval=1 , dtype=tf.float32  ))
    b3 = tf.Variable( tf.random_uniform( [1]   , minval=0 , maxval=1 , dtype=tf.float32  ))
    y_out = tf.sigmoid( tf.matmul( h2,m3 ) + b3 )
    
    
    ### loss
    # loss : sum of the squares of y0 - y_out
    loss = tf.reduce_sum( tf.square( y0 - y_out ))
    
    optimizer = tf.train.GradientDescentOptimizer(1.0)
    train = optimizer.minimize(loss)


    ###data to test after training 
    x_test = [[-1,-1,1,1],[-1,1,1-1]]
    y_test = [[0],[0]]
    # place holder values needed to feed dictionary to the sess.run
    xtest = tf.placeholder(dtype=tf.float32)
    ytest = tf.placeholder(dtype=tf.float32)
    ### training
    # run 500 times using all the X and Y
    # print out the loss and any other interesting info
    with tf.Session() as sess:
      sess.run( tf.global_variables_initializer() )
      for step in range(2000) :
        sess.run(train)
    
      results = sess.run([m1,b1,m2,b2,m3,b3,y_out,loss])
      labels  = "m1,b1,m2,b2,m3,b3,y_out,loss".split(",")
      for label,result in zip(*(labels,results)) :
        print ("")
        print (label)
        print (result)


      print("test data")
      test_results = sess.run([loss],feed_dict = { xtest:X,ytest:y})
      print(loss, " loss")
print("Pattern 1")
neural(X,y)
#neural(xaa,y_aa)
#neural([[1.,0.]],[[1.,0.]])

#neural([[0.,1.]],[[0.,1.]])
#for i,j in zip(xaa,y_aa):
#    neural(i,j)

Saving FinalData.csv to FinalData (6).csv
Pattern 1

m1
[[-1.6005987   1.6327767  -0.7142053   2.831324  ]
 [-1.7806052  -0.75919217  0.7681507   2.3264039 ]
 [ 2.642024    1.4289435   0.6109763  -1.097911  ]
 [ 1.9693528  -0.7845952   1.1320543  -1.4237556 ]]

b1
[ 3.4827511  2.6089838 -0.3808391  3.4249513]

m2
[[ 6.1449776]
 [-3.4603808]
 [-1.9427415]
 [ 5.1711617]]

b2
[-4.942068]

m3
[[10.244115]]

b3
[0.05616748]

y_out
[[0.01058879]
 [0.00977618]
 [0.99344015]
 [0.98999035]
 [0.01058879]
 [0.00977618]
 [0.99344015]
 [0.98999035]]

loss
0.00070184167
test data
Tensor("Sum_6:0", shape=(), dtype=float32)  loss


In [25]:
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  9 13:16:03 2019

@author: CDS
"""

import pandas as pd
import tensorflow as tf
import io
import numpy as np


xaa = [[1,-1,1,-1]]
y_aa = [[1]]

X = xaa
y = y_aa



#NN that takes 9 inputs and returns 1 output via 2 hidden layers for size conversion
def neural(x,y_):
    ### induction
    # 1x9 input -> 9x9 hidden sigmoid -> 9x1 hidden sigmoid -> 1x1 sigmoid output
    
    # Layer 0 = the x2 inputs
    x0 = tf.constant( x  , dtype=tf.float32 )
    y0 = tf.constant( y_ , dtype=tf.float32 )
    
    # Layer 1 = the 9x9 hidden sigmoid
    m1 = tf.Variable( tf.random_uniform( [4,4] , minval=0 , maxval=1 , dtype=tf.float32  ))
    b1 = tf.Variable( tf.random_uniform( [4]   , minval=0 , maxval=1 , dtype=tf.float32  ))
    h1 = tf.sigmoid( tf.matmul( x0,m1 ) + b1 )

    # Layer 2 = the 9x1 hidden sigmoid
    m2 = tf.Variable( tf.random_uniform( [4,1] , minval=0 , maxval=1 , dtype=tf.float32  ))
    b2 = tf.Variable( tf.random_uniform( [1]   , minval=0 , maxval=1 , dtype=tf.float32  ))
    h2 = tf.sigmoid( tf.matmul( h1,m2 ) + b2 )
    
    # Layer 3 = the 1x1 sigmoid output
    m3 = tf.Variable( tf.random_uniform( [1,1] , minval=0 , maxval=1 , dtype=tf.float32  ))
    b3 = tf.Variable( tf.random_uniform( [1]   , minval=0 , maxval=1 , dtype=tf.float32  ))
    y_out = tf.sigmoid( tf.matmul( h2,m3 ) + b3 )
    
    
    ### loss
    # loss : sum of the squares of y0 - y_out
    loss = tf.reduce_sum( tf.square( y0 - y_out ))
    
    optimizer = tf.train.GradientDescentOptimizer(1.0)
    train = optimizer.minimize(loss)


    ###data to test after training 
   
    ### training
    # run 500 times using all the X and Y
    # print out the loss and any other interesting info
    with tf.Session() as sess:
      sess.run( tf.global_variables_initializer() )
      for step in range(2000) :
        sess.run(train)
    
      results = sess.run([m1,b1,m2,b2,m3,b3,y_out,loss])
      labels  = "m1,b1,m2,b2,m3,b3,y_out,loss".split(",")
      for label,result in zip(*(labels,results)) :
        print ("")
        print (label)
        print (result)
        m2data = m2
    
print("Pattern 1")
neural(X,y)


out = np.array([[1,-1,1,-1]]) * np.array([0.4,0.25,.46,0.59])
print(out)
#neural(xaa,y_aa)
#neural([[1.,0.]],[[1.,0.]])

#neural([[0.,1.]],[[0.,1.]])
#for i,j in zip(xaa,y_aa):
#    neural(i,j)

Pattern 1

m1
[[0.7395955  0.29427984 0.47218776 0.2064171 ]
 [0.11742748 0.729991   0.8174824  0.76535153]
 [0.70689315 0.5667313  0.5876685  0.7125137 ]
 [0.10021523 0.4785223  0.85096616 0.04859955]]

b1
[0.8413045  0.32899797 0.8260817  0.73608005]

m2
[[0.85043156]
 [0.85270077]
 [0.2819618 ]
 [0.31492716]]

b2
[0.86871153]

m3
[[2.3956223]]

b3
[2.595948]

y_out
[[0.99180824]]

loss
6.7105e-05
[[ 0.4  -0.25  0.46 -0.59]]


In [0]:
import pandas as pd
import tensorflow as tf
import io

### constant data
'''
xaa = [[1,1,1,-1,-1,-1,1,1,1]]
y_aa = [[1]]
'''
col_names = ['Y','A1','A2','A3','A4','A5','A6','A7','A8','A9']
from google.colab import files
uploaded = files.upload()

pima = pd.read_csv(io.StringIO(uploaded['FinalData.csv'].decode('utf-8')),header = 0,names = col_names)
# load dataset
#pima = pd.read_csv("C:/Users/CDS/Desktop/FinalData.csv", header=0,names=col_names)
pimaObj = pima.iloc[:,:].values

#split dataset in features and target variable
feature_cols = ['A1','A2','A3','A4','A5','A6','A7','A8','A9']
X = pima[feature_cols] # Features
target = ['Y']
y = pima[target] # Target variable

X = X.astype('int')
y = y.astype('int')

Saving FinalData.csv to FinalData (1).csv


In [26]:
0.4+-0.25+0.46+-0.59

0.02000000000000013